version: "3.1"
services:
  app:
    build: .
    # depends_on:
    #   - db
    # links:
    #  - db
    ports:
      - "5000:5000"
    env_file:
      - db/app.env
    # Needed to wait for the initialization of the mysql database
  # db:
  #   image: mysql:5.7.13
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/:ro
  #     - ./mysql-data:/var/lib/mysql
#volumes:
#  mysql-data:
