version: "3.7"

services:
  redis:
    image: redis:6.0.6
    command: redis-server --requirepass root --appendonly yes
    container_name: redis
    restart: always
    volumes:
      - "./container_volumes/redis:/data"
  nginx:
    image: denizgokcin/gjg-backend-challenge-nginx
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./container_logs/nginx/log:/var/log/nginx"
  flask:
    image: denizgokcin/gjg-backend-challenge-app
    build: ./flask
    container_name: flask
    restart: always
    volumes:
      - "./container_logs/flask/log:/var/log/wsgi"
volumes:
  container_volumes:
  container_logs:
