version: "3.7"

services:
  flask:
    image: denizgokcin/gjg-backend-challenge-app
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    networks:
      - app
    volumes:
      - "./container_logs/flask/log:/var/log/wsgi"
  redis:
    image: redis:6.0.6
    command: redis-server --requirepass root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app
    volumes:
      - "./container_volumes/redis:/data"

  nginx:
    image: denizgokcin/gjg-backend-challenge-nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    depends_on:
      - flask
    networks:
      - app
    volumes:
      - "./container_logs/nginx/log:/var/log/nginx"
volumes:
  container_volumes:
  container_loggs:

networks:
  app:
    driver: overlay
