version: "3.1"
services:
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
    env_file:
      - db_files/app.env
  db:
    image: mysql:5.7.31
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/:ro
      - ./mysql-data:/var/lib/mysql
volumes:
    mysql-data:

