version: "3.7"

services:
  redis:
    image: redis:6.0.6
    command: redis-server --requirepass root
    container_name: redis
    restart: always
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./container_logs/nginx/log:/var/log/nginx"
  flask:
    build: ./flask
    container_name: flask
    restart: always
    volumes:
      - "./container_logs/flask/log:/var/log/wsgi"
